#---------------------
#Work section
projects:
  - {name: Chirply, category: Ruby on Rails, folder: 'proj-1'}
  - {name: CrossFit KGB, category: Web Design, folder: 'proj-2'}
  - {name: FilmMaker, category: WordPress, folder: 'proj-3'}
  - {name: Landon Hotel, category: Web Design, folder: 'proj-4'}
  - {name: ReDeSign, category: Graphic Design, folder: 'proj-5'}
  - {name: Survivor Speak, category: Graphic Design, folder: 'proj-6'}
  - {name: Topical Roots, category: WordPress, folder: 'proj-7'}
  - {name: White Noise, category: WordPress, folder: 'proj-8'}
  - {name: White Noise, category: WordPress, folder: 'proj-9'}
  - {name: White Noise, category: WordPress, folder: 'proj-10'}
  - {name: White Noise, category: WordPress, folder: 'proj-11'}
  - {name: White Noise, category: WordPress, folder: 'proj-12'}

# clients
clients:
  - {
    name: Lance E.,
    title: Director,
    company: Vacationland,
    project: 'proj-3',
    folder: 'client-1',
    quote: "Preston is a thoughtful, resourceful designer. His solutions to all of my web needs were simple and elegant. I always felt like he was working hard to go the extra mile and he was confident that he could tackle any request, even if the solution wasn't immediately apparent. He was fast and reliable and I loved the work that he did. I've already recommended him to several friends in the film world."
    }
  - {
    name: Barack O.,
    title: POUTS,
    company: USA,
    project: 'proj-5',
    folder: 'client-2',
    quote: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
    }
  - {
    name: Jerk F.,
    title: Lead Asshole,
    company: United Pants, Inc,
    project: 'proj-1',
    folder: 'client-3',
    quote: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.'
    }
