#---------------------
#Work section
projects:
  - {name: Chirply, category: Ruby on Rails, folder: 'proj-1'}
  - {name: CrossFit KGB, category: Web Design, folder: 'proj-2'}
  - {name: FilmMaker, category: WordPress, folder: 'proj-3'}
  - {name: Landon Hotel, category: Web Design, folder: 'proj-4'}
  - {name: ReDeSign, category: Graphic Design, folder: 'proj-5'}
  - {name: Survivor Speak, category: Graphic Design, folder: 'proj-6'}
  - {name: Topical Roots, category: WordPress, folder: 'proj-7'}
  - {name: White Noise, category: WordPress, folder: 'proj-8'}

# clients
clients:
  - {
    name: Lance Edmands,
    title: Director,
    company: Vacationland,
    project: 'proj-3',
    folder: 'client-1',
    quote: 'Preston is just the best!!!'
    }
  - {
    name: Barack Obama,
    title: POUTS,
    company: USA,
    project: 'proj-5',
    folder: 'client-2',
    quote: 'Wow! What a thrill to have spoken to the wisest man this side of the delta.'
    }
  - {
    name: Jerk Face,
    title: Lead Asshole,
    company: United Pants, Inc,
    project: 'proj-1',
    folder: 'client-3',
    quote: 'FUCK!'
    }
